// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPIWallet_CodeFirstEFCore.Models;

namespace UPIWallet_CodeFirstEFCore.Migrations
{
    [DbContext(typeof(UPIWalletContext))]
    partial class UPIWalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UPIWallet_CodeFirstEFCore.Models.TransactionModel", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPI1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UPI1");

                    b.ToTable("TransactionModels");
                });

            modelBuilder.Entity("UPIWallet_CodeFirstEFCore.Models.UPIModel", b =>
                {
                    b.Property<string>("UPI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UPI");

                    b.ToTable("UPIModels");
                });

            modelBuilder.Entity("UPIWallet_CodeFirstEFCore.Models.TransactionModel", b =>
                {
                    b.HasOne("UPIWallet_CodeFirstEFCore.Models.UPIModel", "UPI")
                        .WithMany("TransactionModel")
                        .HasForeignKey("UPI1");
                });
#pragma warning restore 612, 618
        }
    }
}
